version: "3"

services: 
    web:
        restart: always
        build: 
            context: .
            dockerfile: ./Dockerfile.prod
        command: gunicorn SocialProject.wsgi:application --bind 0.0.0.0:8000
        expose: 
            - 8000:8000
        env_file: 
            - ./.env.prod
        depends_on:
            - db
            - daphne
    db:
        image: postgres:12.0-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        env_file: 
            - ./.env.prod.db
    redis:
        restart: 'on-failure'
        image: "redis:alpine"
        ports: 
            -"6379:6379"
    daphne:
        build: .
        command: daphne SocialProject.asgi:application --port $PORT --bind 0.0.0.0
        environment: 
            - REDIS_HOST=redis
        depends_on: redis
    nginx:
        build: 
            build: ./nginx
            ports: 
                - 1337:80
            depends_on: 
                - web
volumes: 
    postgres_data: