version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres
        environment:
          POSTGRES_USER: $SQL_USER
          POSTGRES_PASSWORD: $SQL_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: chatApp-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          name: Install App Dependencies
          command: |
            pip install virtualenv
            virtualenv venv
            source venv/bin/activate
            pip install -r requirements.txt
            echo "done installing dependencies"
      - save_cache:
          key: chatApp-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - '~/venv'
      - run:
          name: Run Unit Tests
          command: |
            python manage.py test
workflows:
  my_workflow:
    jobs:
      - build:
          context: 
            - chatAppContext