version: 2.1
orbs:
  heroku: circleci/heroku@x.y
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/python:3.8
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres
        environment:
          POSTGRES_USER: $SQL_USER
          POSTGRES_PASSWORD: $SQL_PASSWORD
    steps:
      - checkout
      - run:
          name: Virtual Environment Runs
          command: |
            sudo pip install pipenv
            pipenv install -r requirements.txt
      - run:
          name: Database runs
          command: |
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
      - run:
          name: Run Unit Tests
          command: |
            pipenv run python manage.py test
  deploy:
      - heroku/deploy-via-git:
          post-steps:
            - run: echo "POST STEPS"
          pre-steps:
            - run: echo "PRE STEPS"


      
workflows:
  my_workflow:
    jobs:
      - build:
          context: 
            - chatAppContext
      - deploy: