version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres
        environment:
          POSTGRES_USER: $SQL_USER
          POSTGRES_PASSWORD: $SQL_PASSWORD
    steps:
      - checkout
      - restore_cache:
          key: chatApp-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: 
          name: Install App Dependencies
          command: |
            echo $SECRET_KEY
            pip install pipenv
            pipenv --python 3.8
            pipenv shell
            pipenv install
      - run:
          name: Run Unit Tests
          command: |
            python manage.py test
workflows:
  my_workflow:
    jobs:
      - build:
          context: 
            - chatAppContext